### ISSUE TITLE
Display widgets using a max-width

### ISSUE THREAD

**Issue by 128k** [usyyy/usyyy.github.io#1]
When resizing the window the widgets continue to fill the page meaning on a large enough display, they are all inline.  We should set a max-width so they are at most 3 per row.  
![screen shot 2017-03-19 at 14 05 43](https://cloud.githubusercontent.com/assets/6607304/24081514/282e979c-0cad-11e7-81e0-02b337200d11.png)

**Comment by omfgtora** [comment]
+1

on a normal 1920x1080 resolution, you have a row of 5 then a single on the row below it. This should be kept at 3x3 until a minimum width of 2116px is reached which would allow all 6 widgets to display in one row.
